Feature/#14
ak03120/intern-kumada pull request #26
Opened 2023-03-16 10:32 UTC by ak03120

Close #14 
## Checklist for Developer
- [x] 最新のdevelopブランチをPullした。Pulled the latest develop branch.
  - できない理由 Reason not to do: 
- [x] Pull RequestをIssueに紐付けた。Connected with the issue.
- [x] 自分をAssignした。Assigned yourself.
- [x] レビュワーを指定した。Assigned reviewer.

## 📝 そのほかの関連するIssue / Related issues other than connected one

- #14 

## ⛏ 変更内容 / Details of Changes

- Bookインターフェースにidを追加しました。
- @Outputを使用してデータの受け渡しができるようにしました。

## 📸 スクリーンショット / Screenshots

![Mar-16-2023 19-30-56](https://user-images.githubusercontent.com/123559879/225590108-3596e7e0-8020-4061-8984-8182fd44db9b.gif)

## レビューするポイント (Points for review):

 - 削除ボタンを押した時にそのカードが消える

2023-03-16 10:36 UTC, hikaru-nakamura-thedott requested changes

2023-03-16 10:36 UTC, hikaru-nakamura-thedott commented on intern-book-app/src/app/pages/list/list.component.ts
> +  cbook: Book = {id: 0, name: '', detail: '', evaluation: 0};
cってなんですか？

2023-03-17 08:30 UTC, ak03120 commented on intern-book-app/src/app/pages/list/list.component.ts
> +  cbook: Book = {id: 0, name: '', detail: '', evaluation: 0};
cbookをcardBookに変更しました。

2023-03-20 08:48 UTC, hikaru-nakamura-thedott approved these changes

2023-03-20 08:48 UTC, hikaru-nakamura-thedott commented on intern-book-app/src/app/pages/list/list.component.ts
> +      id: this.bookList[this.bookList.length-1].id+1, // this.bookList.lengthの場合ID被りが発生する。
```typescript
id: this.bookList.slice(-1)[0].id+1
```

とかでも行けるね。

2023-03-20 08:48 UTC, merged

2023-03-21 00:39 UTC, ak03120 commented on intern-book-app/src/app/pages/list/list.component.ts
> +      id: this.bookList[this.bookList.length-1].id+1, // this.bookList.lengthの場合ID被りが発生する。
なるほど！ためになります！